server:
  # 应用服务 WEB 访问端口
  port: 82
  servlet:
    context-path: /admin
spring:
  application:
    # 应用名称
    name: springcloud-oycblog-admin
  cloud:
    # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
    # Nacos认证信息
    nacos:
      discovery:
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public
        password: nacos
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: 146.56.192.87:8848
        username: nacos

